### ISSUE TITLE
SubDomain değişikliği sonucu linklerin bozulması

### ISSUE THREAD

**Issue by cahmetcan** [YEmreAk/IstanbulUniversity-CE#20]
## Hata Özeti 🐞
Üniversite isminin iü'den iüc'ye dönüşmesi sonucu subdomain güncellenmiş. Fakat bazı linkler hala iuce.yemreak.com e yönlendiriyor.

## Hatayı Engelleme Adımları:
1. tüm bu linkleri iucce ile güncellemek :)

**Comment by yemreak** [comment]
Selam, feedback icin teşekkür ederim. Hangi bağlantılarda sorun var onlardan bahsedebilir misin, projeyi clone'layip arama yaptigimda iuce.yemreak.com linkleri goremedim @cahmetcan

**Comment by cahmetcan** [comment]
aslında yanlış repoya issue açmışım. https://lib.yemreak.com/iuce bloğundaki linkler yanlış yere yönlendiriyor @yemreak

**Comment by yemreak** [comment]
> aslında yanlış repoya issue açmışım. https://lib.yemreak.com/iuce bloğundaki linkler yanlış yere yönlendiriyor @yemreak

Duzelttim teşekkür ederim :)
