### ISSUE TITLE
Link url i hatalı

### ISSUE THREAD

**Issue by afozbek** [YEmreAk/IstanbulUniversity-CE#30]
Projenin [bu](https://github.com/YEmreAk/IstanbulUniversity-CE/blob/master/4.%20S%C4%B1n%C4%B1f%201.%20D%C3%B6nem%20Notlar%C4%B1/Bili%C5%9Fim%20Proje%20Geli%C5%9Ftirme/Ders%20%C4%B0%C3%A7eri%C4%9Fi/2018%20Slaytlar%C4%B1/README.md) kısmındaki linklerin tamamı **hatalıdır**.

**Comment by yedhrab** [comment]
Teşekkürler ✨

**Comment by yedhrab** [comment]
Tüm sorunlu linkler düzeltildi (56d5a06)
