### ISSUE TITLE
⚠ DE dosyası sorunlu çalışmakta

### ISSUE THREAD

**Issue by asmaamirkhan** [YEmreAk/IstanbulUniversity-CE#56]
## Hata Özeti 🐞

- Projenin [bu](https://github.com/YEmreAk/IstanbulUniversity-CE/blob/master/2.%20S%C4%B1n%C4%B1f%201.%20D%C3%B6nem%20Notlar%C4%B1/Differantial%20Equations/%C3%96%C4%9Frenci%20Notlar%C4%B1/Ders%20Notlar%C4%B1%20DE%20~%20Asma%20Mirkhan.pdf) dosyası sorunlu çalışmakta

![image](https://user-images.githubusercontent.com/45575570/71477289-330cb700-27fa-11ea-956d-665158e66199.png)
 
> İndirilince de beyaz sayfalardan oluşan bir dosya gelmekte

## Hatayı Engelleme Adımları:

1. Dosyanın çalışan versiyonu [burada](https://github.com/YEmreAk/IstanbulUniversity-CE/blob/master/2.%20S%C4%B1n%C4%B1f%201.%20D%C3%B6nem%20Notlar%C4%B1/Differantial%20Equations/%C3%96%C4%9Frenci%20Notlar%C4%B1/2018%20Ders%20Notlar%C4%B1%20DE%20~%20Asma%20Mirkhan.pdf) yer almakta, bozuk olan silinip çalışan olan bırakılabilir

**Comment by yedhrab** [comment]
Teşekkürler, bunu düzelten bir PR yapabilir misin acaba?
