### ISSUE TITLE
Changelog sorunlu bağlantılar içermekte

### ISSUE THREAD

**Issue by asmaamirkhan** [YEmreAk/IstanbulUniversity-CE#61]
## Hata Özeti 🐞

- Projenin [Changelog'undaki](https://github.com/YEmreAk/IstanbulUniversity-CE/blob/master/CHANGELOG.md)  bağlantılar ilgili commit'e yönlendirmemekte, 404 vermekte

## Hatayı Engelleme Adımları:

1. `/YEmreAk/IstanbulUniversity-CE` eksik
2. `diff` sorgusu yapılandırılmalı
3. `https`'ten sonraki `%3A` karakteri kaldırılmalı

**Comment by yedhrab** [comment]
👨‍🔧 Düzeltildi 9d161bd
